# Generated by Django 2.1.3 on 2021-07-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_and_brands', '0002_auto_20210714_0520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brand_id',
            new_name='brand',
        ),
    ]
